### PR TITLE
Fix ffmpeg5 compilation error

### PR DESCRIPTION
**Pull request by mkkot**
Easy fix, but needs testing. I can see it compiles and starts, but don't have hardware connected to pc with ffmpeg5. If someone can compile, run and confirm, I'll be grateful. Otherwise I will try to set up some live system for the box where I have the hardware and test it there.

### CODE REVIEW

**Comment by jakemoroni** [comment]
Tested, working with my system.

**Comment by jakemoroni** [comment]
Tested and working with my system (Ubuntu 22.04). Thanks!
